# Limpieza de la Bitácora de Piso

In [3]:
import pandas as pd

# Ajusta esta ruta si el archivo no esta en la misma carpeta que este notebook
archivo_entrada = r"C:\Users\yarem\Desktop\Actividad_4.1\Analisis GAC Full7agosto 2026(Bitacora de Piso).csv"

# encoding="utf-8-sig" quita el BOM del archivo (evita que la primera columna se lea como "Fecha" con caracteres raros al inicio)
df = pd.read_csv(archivo_entrada, encoding="utf-8-sig")

print("Forma original:", df.shape)
df.head()

Forma original: (234, 30)

,Fecha,Nombre Cliente,Telefono,Asesor,Esatus Lead,PDM,SDC,Estatus de SDC,Venta,Temperatura,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,04/01/2025,Ubaldo Cruz Hernandez,NaN,Aurelio,Activo,True,False,NaN,False,Lead InteresBajo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04/01/2025,Olivia Cabello,NaN,Pedro,Activo,False,False,NaN,False,Lead InteresBajo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,04/02/2025,Ana Laura Espinoza,NaN,Mauricio,Activo,True,True,Analisis,True,Lead Interes Alto,...,NaN,NaN,NaN,NaN,NaN,NaN,Items,Items,items,items
3,04/02/2025,Elvis Sanchez,NaN,Aurelio,Activo,False,False,NaN,False,Lead InteresBajo,...,NaN,NaN,NaN,NaN,NaN,NaN,Aurelio,Activo,Aprobada,Lead Interes Medio
4,04/03/2025,Ariel Fernando López,NaN,Alan,Activo,True,False,NaN,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Pedro,Cerrado,Condicionada,Lead InteresBajo

## 2. Eliminar columnas

Se eliminan `Teléfono` y `Estatus de SDC`

In [4]:
# quitamos espacios sobrantes en los nombres de columna (ej. "Telefono " -> "Telefono")
df.columns = df.columns.str.strip()

# las columnas "Unnamed" son las columnas sin encabezado real que traen "Items"
columnas_items = [col for col in df.columns if col.startswith("Unnamed")]

columnas_a_eliminar = ["Telefono", "Estatus de SDC"] + columnas_items
df = df.drop(columns=columnas_a_eliminar)

print("Columnas eliminadas:", columnas_a_eliminar)
print("Forma tras eliminar columnas:", df.shape)

Columnas eliminadas: ['Telefono', 'Estatus de SDC', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']
Forma tras eliminar columnas: (234, 16)

In [5]:
filas_57_a_67 = range(55, 66)      # fila 57 a 67 de tu hoja
filas_210_a_235 = range(208, 234)  # fila 210 a 235 de tu hoja

df = df.drop(index=list(filas_57_a_67) + list(filas_210_a_235))
df = df.reset_index(drop=True)

print("Forma tras eliminar filas:", df.shape)
print("Filas duplicadas restantes:", df.duplicated().sum())

Forma tras eliminar filas: (197, 16)
Filas duplicadas restantes: 0

In [6]:
for columna in df.columns:
    df[columna] = df[columna].apply(lambda valor: valor.strip() if isinstance(valor, str) else valor)

# normalizar Fecha a mm/dd/aaaa siempre con 2 digitos
df["Fecha"] = pd.to_datetime(df["Fecha"], format="%m/%d/%Y", errors="coerce").dt.strftime("%m/%d/%Y")

print("Ejemplo de fechas:", df["Fecha"].head(5).tolist())

Ejemplo de fechas: ['04/01/2025', '04/01/2025', '04/02/2025', '04/02/2025', '04/03/2025']

In [7]:
df["Esatus Lead"] = df["Esatus Lead"].replace({"venta": "Venta"})
df["Temperatura"] = df["Temperatura"].replace({"Lead InteresBajo": "Lead Interes Bajo"})

print("Esatus Lead:", sorted(df["Esatus Lead"].dropna().unique()))
print("Temperatura:", sorted(df["Temperatura"].dropna().unique()))

Esatus Lead: ['Activo', 'Cerrado', 'Finalizado', 'Venta']
Temperatura: ['Ebullición', 'Lead Interes Alto', 'Lead Interes Bajo', 'Lead Interes Medio', 'Tibio']

In [8]:
nulos_antes = int(df.isna().sum().sum())
df = df.fillna("Sin dato")

print(f"Se rellenaron {nulos_antes} valores faltantes con 'Sin dato'")

Se rellenaron 1473 valores faltantes con 'Sin dato'

In [9]:
print("Forma final:", df.shape)
print("Valores nulos restantes:", df.isna().sum().sum())
print("Filas duplicadas restantes:", df.duplicated().sum())

archivo_salida = "Bitacora_de_Piso_Limpia.csv"
df.to_csv(archivo_salida, index=False, encoding="utf-8-sig")
print("Archivo guardado como:", archivo_salida)

df.head()

Forma final: (197, 16)
Valores nulos restantes: 0
Filas duplicadas restantes: 0
Archivo guardado como: Bitacora_de_Piso_Limpia.csv

,Fecha,Nombre Cliente,Asesor,Esatus Lead,PDM,SDC,Venta,Temperatura,Inter Gerente,¿Por que no hubo prueba de manejo?,¿Por que no hubo Solicitud de credito?,¿Por que no hubo intervencion del Gerente?,¿Por que no hubo proceso wow?,¿Por que no se ha formalizado la compra?,5 porques clientes de piso,Comentarios
0,04/01/2025,Ubaldo Cruz Hernandez,Aurelio,Activo,True,False,False,Lead Interes Bajo,True,Sí hubo prueba de manejo.,"El cliente acudió con una prima, para ella ser...","Sí hubo interacción del gerente, los cliente s...","Sí hubo proceso wow, se recibío al cliente con...",Tiempo de compra hasta el próximo año.,El cliente llego ocasionalmente antes de llega...,Sin dato
1,04/01/2025,Olivia Cabello,Pedro,Activo,False,False,False,Lead Interes Bajo,True,La clienta piensa acudir con sus hijos para ha...,Es una decisión que prefiere tomar con sus hijos.,Sí hubo intervención del Gerente. Converse con...,"Sí hubo un proceso wow, además de la interacci...",Sin dato,Clienta viene buscando opciones para ella y su...,Sin dato
2,04/02/2025,Ana Laura Espinoza,Mauricio,Activo,True,True,True,Lead Interes Alto,True,"Sí hubo prueba de manejo por la tarde, ya que ...",Ingresa SDC con el perfil de ella y el de su e...,Sí hubo intervención del gerente en las dos vi...,Calificación 5,No se formalizo la venta ya que fue rechazado ...,El cliente visito la agencia porque iba pasand...,Sin dato
3,04/02/2025,Elvis Sanchez,Aurelio,Activo,False,False,False,Lead Interes Bajo,True,El cliente no quiso porque sabe que no se encu...,El cliente comenta que en este momento tiene c...,"Sí hubo intervención y me comento su estatus, ...",Calificación 5,Porque por el momento no cuenta con moviemient...,El Señor Elvis se encuentra evaluando diferent...,Sin dato
4,04/03/2025,Ariel Fernando López,Alan,Activo,True,False,False,Sin dato,True,Sin dato,Sin dato,Sin dato,Sin dato,Sin dato,El cliente se encuentra en busqueda de renovar...,Sin dato